### ISSUE TITLE
Expose/share CycleStreets data layer

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#11]

**Comment by mvl22** [comment]
Here is a screenshot showing the rendering of the underlying journey planner scorings (which combines hundreds of rules). Essentially this is a simplified rendering of cycleability. We could somehow make this available as an exported dataset to get a prototype running more quickly.

Compare the green of the cycleway with the blue (hostile) of the road:

![blackfriars-cyclestreets](https://cloud.githubusercontent.com/assets/361423/24242509/d43f1d04-0faf-11e7-893d-a704891fbe0a.png)

![blackfriars-opencyclemap](https://cloud.githubusercontent.com/assets/361423/24242508/d43eaebe-0faf-11e7-927d-4f7f53b2f93a.png)

**Comment by mvl22** [comment]
There is also the routing browser, containing the same data but more interactive and detailed. It is currently served as GeoJSON on a clickable map, but may be possible to export as a dataset also with a bit of work.

(In the top left there is a score, in this case 100%, but that's currently scrolled up so that you can see the ruleset scorings in the bottom right.)

(We plan to open up all this stuff anyway as public layers, but at the moment the query efficiency is not great so these can be a bit slow to generate, hence why they're not yet available. This could be an objective for the current project if it is identified that this is a way forward.)

![screen shot 2017-03-23 at 10 16 13](https://cloud.githubusercontent.com/assets/361423/24243124/db8e49ca-0fb1-11e7-9ee4-2579813bd31e.png)

**Comment by Robinlovelace** [comment]
Looks done to me.

**Comment by mvl22** [comment]
I've now got this layer exposed experimentally on the Bikedata site:

http://bikedata.cyclestreets.net/cycleability/#18/51.51129/-0.10396/opencyclemap

Be aware that it is not fully optimised for performance.

Obviously next main step is to get the same information available as a raw data export rather than than a map.

**Comment by mvl22** [comment]
> Obviously next main step is to get the same information available as a raw data export rather than than a map.

I've been working today on this and I've got a (slow) prototype for bulking extracting the data. I don't have 100% confidence yet that it is complete, but some manual checks look correct.

I'll upload an extract of the data for Cambridge (as that is the only area currently defined) shortly.

**Comment by Robinlovelace** [comment]
~Sound promising - look forward to it.

**Comment by Robinlovelace** [comment]
Heads up @mvl22 will be good to take a look at this before Tuesday afternoon.

**Comment by Robinlovelace** [comment]
Great work, as illustrated here we can now merge this in with our OSM data: https://github.com/cyipt/cyipt/commit/98b244fe32401a59f7e6c1afd9aa9073175996ba
