### ISSUE TITLE
Allocate cycling potential estimates to OSM data 

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#24]
Initially for Bristol

**Comment by mem48** [comment]
I'm making a fist attempt at this which is working (code and demo data to be uploaded soon).

But an early problem is that the OSM lines do not break at all junctions, 

![image](https://cloud.githubusercontent.com/assets/15819577/24967426/f34f7a3e-1fa1-11e7-92d4-9f85db04f619.png)

See example image, a single line (blue) has different values along its length, due to people splitting off at junctions. Is there a way to split the OSM lines at junctions?

@mvl22 @mvl22 @si-the-pie

**Comment by Robinlovelace** [comment]
Great stuff. Would be greater if you linked to the code that did it.
