### ISSUE TITLE
Set-up website

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#44]
Useful for publishing results.

This will allow easy communication of results.

Working with UoL to set-up a shiny-server instance.

But the domain name is sorted: http://www.cyipt.bike/

**Comment by Robinlovelace** [comment]
@mem48 and @mvl22 pls add any files to be served into the `content` folder here: https://github.com/cyipt/cyipt.bike

Otherwise posts and new pages can be created with `new_post()` and `new_content()`.

See https://bookdown.org/yihui/blogdown/ and https://gohugo.io/overview/configuration/ for docs of how this works.

**Comment by mvl22** [comment]
Just to comment that I'm happy with a Shiny instance in terms of getting something quickly running, but in the slightly-further-ahead term I would like us to make sure we properly investigate an API-driven output, so that the data visualisations are easily repurposable and that we aren't stuck with auto-generated code that (I suspect) gets less and less flexible over time, compared to really tight Javascript with properly separated backend/frontend codebases.

The current pct.bike visualisations for instance are presumably next-to-impossible to embed in a third-party site. A GeoJSON-based API for that would enable that.

To be clear though, for a WP1 perspective, getting things working quickly is quite rightly the correct priority. Just wanted to flag a warning that we don't go too far down this path.

**Comment by mvl22** [comment]
What is cyipt.github.io ? Is that basically deprecated now you have a domain name?

**Comment by Robinlovelace** [comment]
No that serves the website via[ github pages](https://pages.github.com/) and redirects to our domain name.

**Comment by Robinlovelace** [comment]
@mvl22 and @mem48 to demonstrate this please see the image here: http://www.cyipt.bike/cyipt-logo.jpg

That was put there because of a file I put here: https://github.com/cyipt/cyipt.bike/tree/master/content

Note: 'intelligent' files such as .md files create .index.html files in a separate folder on the published site. So about.md generates this: http://www.cyipt.bike/about/

blogdown makes adding content easy - read the docs on that here: https://bookdown.org/yihui/blogdown/
