### ISSUE TITLE
Historic data sources

### ISSUE THREAD

**Issue by mvl22** [cyipt/cyipt#52]
This issue can act as a list of historic data sources, in relation either to usable data or cost-benefit analysis of outcomes.

**Comment by mvl22** [comment]
Value for Money Assessment for Cycling Grants, 2014.

https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/348943/vfm-assessment-of-cycling-grants.pdf

Provides a cost-benefit analysis review of Cycle City Ambition Grant and the Cycling in National Parks Grant, which basically covers the DfT capital expenditure on cycling infrastructure in the roughly three years following the scrapping of Cycling England.

Not clear if this is a compilation of claims by Local Authorities or whether this is a desk study by a DfT person of raw data undertaken consistently.

Includes a useful diagram on PDF page 13:

![screen shot 2017-10-06 at 19 31 13](https://user-images.githubusercontent.com/361423/31292881-f9db3544-aacc-11e7-836b-8588f2998e74.png)

which is followed by a similar diagram for the National Parks schemes.

**Comment by mvl22** [comment]
Cycle City Ambition Monitoring Plan
July 2015

https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/486384/cycle_city_ambition_grant-report.pdf

Contains various data as part of scheme reviews.

**Comment by Robinlovelace** [comment]
Thanks for the issue and the link to CCA monitoring plan. All the work was done after 2011 by the look of it, but it certainly contains loads of useful links. To clarify, this issue is to get historic data from the Route Direct scheme, right?

In any case CCA was an impressive project:

> Background
The CCA programme is a major investment programme from the DfT that aims to support
cycling through capital investment in eight English cities/city regions: Birmingham, Bristol,
Cambridge, Leeds, Greater Manchester, Newcastle, Norwich and Oxford.
In August 2013 funding of £77 million was announced for the CCA programme. Match
funding
