### ISSUE TITLE
Don't recommend cycle streets on B roads

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#72]
Heads-up @johnparkin28 we've noticed cycle streets popping up in some through routes with high levels of traffic - see #70 - this is our solution for now.

Plan A is to use the ref tag and perhaps other info (e.g. `highway=secondary`) to change the recommendation algorithm. Cycle lanes would seem the most common type to change them to. Some could also become light segregated but that would depend on the advice name.

Plan B is to change road traffic levels to preclude these on those routes.

**Comment by mvl22** [comment]
https://wiki.openstreetmap.org/wiki/Highway:International_equivalence

**Comment by johnparkin28** [comment]
Okey dokey, sounds like a plan.

Regards
John Parkin CEng FICE FCIHT FCILT, Professor of Transport Engineering
Deputy Director, Centre for Transport and Society
University of the West of England, Frenchay Campus, Coldharbour Lane Bristol, BS16 1QY, UK
Direct line: +44 (0)117 32 86367      Mobile: +44 (0)7848 029 902
Skype: john.parkin9                           Twitter: @JohnParkin28
Linked In       https://uk.linkedin.com/pub/john-parkin/6/840/89b
Web               http://www1.uwe.ac.uk/et/research/cts
Facebook      https://www.facebook.com/ctsuwe and https://www.facebook.com/UWECivilandEnvironmentalEngineering/
Publications  http://eprints.uwe.ac.uk/view/author/Parkin=3AJohn=3A=3A.html

**Comment by mem48** [comment]
I've been looking into this and I increasing feel that option B is better.

1) I'm uncomfortable in adding a "bodge" to the algorithm that otherwise follows a nice clear set of rules
2) The places where cycle streets are incorrectly recommended nearly always lack an AADT count

See a nice example at https://www.cyipt.bike/recommended/#18/51.45504/-2.60229/mapnik

I did a quick analysis of the AADT levels by OSM road type for the roads where we have an AADT score

highway | min | count | Q1 | mean | median | Q3 | max | mode
-- | -- | -- | -- | -- | -- | -- | -- | --
bridleway | 4 | 43 | 809 | 2059 | 1869 | 4090 | 11501 | 1869
cycleway | 12 | 486 | 2088 | 8110 | 5907 | 9397 | 111865 | 2088
footway | 0 | 1264 | 623 | 3183 | 1623 | 4480 | 39486 | 590
living_street | 105 | 46 | 726 | 7868 | 5866 | 14643 | 19781 | 11436
motorway | 2407 | 7793 | 58522 | 90255 | 89728 | 118551 | 213725 | 87629
motorway_link | 2407 | 1785 | 52590 | 85223 | 85196 | 113983 | 197241 | 54884
path | 199 | 171 | 1342 | 4935 | 2368 | 7704 | 12288 | 12288
pedestrian | 751 | 18 | 1264 | 5209 | 1989 | 9474 | 16377 | 1151
primary | 369 | 159784 | 9342 | 14830 | 13947 | 18903 | 93125 | 13785
primary_link | 1131 | 1520 | 12965 | 21943 | 19044 | 28150 | 131949 | 23659
residential | 0 | 20039 | 486 | 1739 | 1049 | 2204 | 27131 | 509
road | 1530 | 1 | 1530 | 1530 | 1530 | 1530 | 1530 | 1530
secondary | 187 | 53103 | 3609 | 7910 | 6866 | 10915 | 37982 | 9329
secondary_link | 995 | 141 | 6991 | 12799 | 10885 | 16181 | 53102 | 12388
service | 1 | 749 | 590 | 6207 | 2826 | 6782 | 122682 | 11006
steps | 286 | 8 | 1617 | 4556 | 4652 | 6568 | 9710 | 5997
tertiary | 0 | 16054 | 2473 | 5704 | 4761 | 7797 | 29705 | 2262
tertiary_link | 861 | 17 | 17494 | 19186 | 19370 | 21084 | 47879 | 19370
track | 5 | 138 | 24 | 926 | 303 | 1151 | 9895 | 11
trunk | 878 | 118415 | 12874 | 22975 | 19280 | 28121 | 144305 | 16017
trunk_link | 740 | 4294 | 23275 | 47093 | 38842 | 66303 | 143321 | 34939
unclassified | 3 | 7409 | 299 | 2218 | 964 | 2868 | 84973 | 2882

There are a few mismatches like 111,000 cars on a cycleway! Must mostly it is as you would expect. 

I suggest that we increase the traffic level of motorway, trunk, primary, secondary, and tertiary roads from 0 to 2501 when we have no data. This would always exclude cycle streets  (in favour of cycle lanes) except where the speed limit is 40 mph + when the algorithm already kicks in the segregated cycle tracks.

**Comment by Robinlovelace** [comment]
I also like Plan B. Will be in later to discuss. Great quick analysis of the aadt data.

**Comment by mvl22** [comment]
Can we please change, for future readers/maintainers/re-users of the code, the 2501 from a magic number to an explicit constant that is fully-documented at the head of the code.

This is a great example of Martin Fowler's code smell recipe 'Replace Magic Number with Symbolic Constant':
https://refactoring.com/catalog/replaceMagicNumberWithSymbolicConstant.html

**Comment by mem48** [comment]
Done ages ago
