### ISSUE TITLE
CyIPT recommends some very small paths

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#81]
For example this which is not useful (verified at Be Curious today!):

https://www.cyipt.bike/schemes/#16/53.8084/-1.5188/mapnik

![image](https://user-images.githubusercontent.com/1825120/37556686-4f9209f6-29f1-11e8-8f20-934df3adf674.png)

**Comment by mvl22** [comment]
I think a key issue is why such a huge C/B of 65 results - feels like an algorithm issue.

**Comment by mem48** [comment]
There is a 200m minimum threshold for schemes, this one looks especially small as it is wrapped around itself. I wouldn't recommend raising the threshold because you start to get gaps where there really should be infrastructure see https://www.cyipt.bike/schemes/#16/51.5312/-0.2967/grayscale and the difference between the schemes and the recommended infrastructure.

The BCR is due to the poor data we have on the benefits of cycle streets so the uptake model treats them like cycle lanes, but the cost of cycle streets is so low that the BCR comes out very high. I suggest that we change the BCR colour scale to max out at 30, so we don't draw particular attention to these schemes.

**Comment by Robinlovelace** [comment]
I think these schemes could be filtered-out at the scheme creation (segment aggregation) stage: if they do not connect to any other infrastructure, existing or proposed (as with this one) I think it could be removed. An 'after Friday' job I imagine.

**Comment by jf1** [comment]
Could introducing a 'minimum cost' filter be a useful way to address this?

This would also enable someone eg only interested in very large schemes to set a high minimum cost.

If deemed helpful, it could be useful to preset the minimum cost to eg £20k rather than £0

**Comment by mem48** [comment]
> Could introducing a 'minimum cost' filter be a useful way to address this?

@jf1 The minimum benefits filter does this

**Comment by jf1** [comment]
> The minimum benefits filter does this

Not for me it doesn't - if I set a minimum benefit of £50k that filter performs as expected, and the results still include low-cost schemes such as this example: Total cost in £: 4,899 (Its benefit was >50k)

My suggestion is that rather than have CyIPT filter them out at an earlier stage they could be suppressed in the UI by a pre-set filter that the user could adjust if they're keen to see cheap schemes too.

**Comment by mem48** [comment]
Surely the low-cost high benefit scheme is exactly the kind of results we should be promoting not hiding?

There is a separate issue that I think CyIPT overestimates the benefits of low-cost schemes, but it is still a prototype and that is one of its limitations.

**Comment by jf1** [comment]
> Surely the low-cost high benefit scheme is exactly the kind of results we should be promoting not hiding?

That's fine when that's what a user wants to see, but it may be consider distracting if it's not what the user wants to see. What if someone has been tasked with defining the large schemes first?

Quick wins are usually an ongoing process whereas area-wide network planning is a structured task, or at least it has been the way Brian Deegan is overseeing things here. (ps. He's at a GM meeting on Friday afternoon, so I doubt he'll be attending the workshop).
