### ISSUE TITLE
Update auto response to emails

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#85]
Question for @mvl22: can we create auto-replies from the email account, to say 'If it's a bug please report it at https://github.com/cyipt/cyipt '? I think we could also use this as a way to get more feedback.

Context: there's a typo, will open a new issue on that.

**Comment by mvl22** [comment]
> If it's a bug please report it at https://github.com/cyipt/cyipt

To be honest, I don't think that's a very user-friendly thing for our audience of likely LA and consultancy people - they would need to register a Github account and also thus have their identity (or at least a username) public. I suspect many will simply not bother doing this, given the transactional cost of setting up an account just in order to give feedback.

Given that we don't seem to get vast numbers of bug reports, I'd prefer for now that we manually transfer these to Github, though it was a perfectly valid suggestion!

**Comment by Robinlovelace** [comment]
OK, closing for now.
