### ISSUE TITLE
Write code that downloads all possible cycle paths 

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#9]
Using the osmdata package:

- [x] All highways marked as `bicycle=yes`
- [x] All cycleways
- [x] All relations that define cycleways (see https://github.com/osmdatar/osmdata/issues/45 )

**Comment by Robinlovelace** [comment]
Link it back to this (out of date now I know!): http://leeds.gisruk.org/abstracts/GISRUK2015_submission_71.pdf

**Comment by mvl22** [comment]
> All highways marked as `bicycle=yes`

That's definitely not correct - that just says that bicycles are legally permitted to use it, i.e. it's an access tag.

If you want things that imply the presence of bicycle infrastructure or a route which bicycles may follow (which often may not have any infrastructure other than signage):

 * Members of all Relations having `network=`{lcn|ncn}` (personally I would skip rcn)
 * Ways with `highway=cycleway`
 * Ways with `highway=footway` with `bicycle=yes`
 * Ways having `cycleway=lane`
 * Ways having `cycleway=track`
 * Ways having `cycleway=share_busway`
 * The above but with left/right variants, e.g. `cycleway:left`

will get you most of the way.

This page will blow your mind:
http://wiki.openstreetmap.org/wiki/Bicycle

**However**, these do not imply any sort of quality. Only a much more detailed ruleset which deals with the kinds of things listed here will get you that:

https://www.cyclestreets.net/api/v2/journey.plan/

**Comment by mpadge** [comment]
For what my opinion on this might be worth: @mvl22's statement in #10 is exactly right - there can never be a complete label-based solution, because all databases, mapservers, whatever, are entirely reliant on labels, and labels are alway fallible. I'd thus suggest it'll never be possible to extract **all** possible cycle paths, but what you will certainly be able to do is extract the most probable cycling paths between A and B. There can also be no single solution to this issue in general because there can never be a single path, for cycling or otherwise, between any two points. 

Solution requires two things:
1. Probabilistic routing engine - Robin, you already know about this, and it's coming along in leaps and bounds. I'll keep you informed.
2. Real data on where people actually ride (such as the ubiquitous [strava example](https://www.theguardian.com/lifeandstyle/2016/may/09/city-planners-cycling-data-strava-tracking-app)) and ability to feed that into routing engine.

Latest:
1. Abstract to be submitted to UseR Brussels and hopefully introduced there
2. Deadline for operational package: September

I'd say it's not worth the effort of constructing a detailed ruleset - you'd be doing the equivalent of trying to program an AI module by explicitly implementing each component. You need a flexible system that can give you multiple answers, and the ability of that system to respond to actual behavioural data. To simply get such a system rolling, near enough in the simple sense of messy OSM labels is almost certainly good enough.

The rest will all be possible before the end of this year ...

**Comment by mvl22** [comment]
> There can also be no single solution to this issue in general because there can never be a single path, for cycling or otherwise, between any two points.

See #11.

**Comment by mvl22** [comment]
> where people actually ride (such as the ubiquitous strava example)

I would obviously very strongly caution against using that dataset for the purposes being discussed here. It is so far from representing desire lines that meet Space for Cycling principles.

**Comment by Robinlovelace** [comment]
They are all in there - but not identified as 'cycle paths' yet but think that's a separate issue.
